version: '3'

services:
  backend:
    image: 'real-estate-app-backend:latest'
    build:
      context: .
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/propertysalessystem
      - SPRING_DATASOURCE_USERNAME=dobos
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - GOOGLE_CLIENT_ID=748440303117-g6l82pldugqekitgjo9pt1iruheaqubh.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - JWT_HASH_SECRET=i!@#!quhi2h428417as@!#adskj12!&*1aslkq!$nw
      - OAUTH2_REDIRECT_URL=http://localhost:3000/oauth2/redirect
  db:
    image: 'postgres:15.3-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=dobos
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=propertysalessystem
  frontend:
    image: 'real-estate-app-frontend:latest'
    container_name: frontend
    ports:
      - "3000:80"